[package]
name = "qr_lib"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"

[lib]
name = "qr_lib"
crate-type = ["lib"]