name: Build & test

on:
  pull_request:
    branches:
      - master

jobs:
  rust-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Run backend tests
        run: make tests

  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2

      - name: 🔧 Install yarn
        run: npm install -g yarn

      - name: Get yarn cache path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: ⚡ NPM Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: 🔧 Install dependancies
        run: yarn

  build:
    runs-on: ubuntu-latest
    needs: rust-test

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Run collector
        run: make collector

      - name: ⚙ Run cleaner
        run: make cleaner

      - name: 📌 Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Update data" || true
          git push
