name: Build & test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: 🔨 Install system dependancies
        run: |
          sudo apt install -y clang libclang-dev libopencv-dev

      - name: 🔧 Install stable toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          profile: minimal
          toolchain: stable

      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('./rust/Cargo.lock') }}

      - name: ⚙ Run backend tests
        run: make tests

      - name: ⚙ Run collector
        run: make collector

      - name: 📌 Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git commit -am "Update frontend data" || true
          git push

      - name: 🔧 Install yarn
        run: npm install -g yarn

      - name: Get yarn cache path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: ⚡ NPM Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: 🔧 Install dependancies
        run: yarn
