name: Cleaner

on:
  schedule:
    - cron: '25 2 * * *'


jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🔧 Install rust dependancies
        uses: ./.github/workflows/rust-install

      - name: ⚙ Run cleaner
        run: make cleaner

      - name: 📌 Commit changes
        uses: ./.github/workflows/commit-changes
        with:
          message: 'Remove old QR files'
