name: CLI

on:
  pull_request:
    branches:
      - master
    paths:
      - 'cli/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/paritytech/ci-unified:bullseye-1.81.0-2024-11-19-v202411281558
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Install rust dependencies
        uses: ./.github/workflows/rust-install

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo check
        run: cargo check

      - name: Cargo clippy
        run: cargo clippy -- -D warnings

      - name: Cargo test
        run: cargo test
